# Generated by Django 5.1.1 on 2024-12-02 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pic',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile_pic',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.users'),
        ),
    ]
