# Generated by Django 5.1.1 on 2024-12-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_profile_pic_profile_pic_alter_profile_pic_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Music', 'Music'), ('Sports', 'Sports'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Workshop', 'Workshop')], max_length=50)),
            ],
        ),
    ]
