# Generated by Django 5.1.1 on 2024-12-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_total_price_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_id', models.CharField()),
                ('razorpay_payment_id', models.CharField()),
                ('razorpay_order_id', models.CharField()),
                ('razorpay_signature', models.CharField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.users')),
            ],
        ),
    ]
