# Generated by Django 5.1.1 on 2024-12-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='razorpay_signature',
        ),
    ]
