# Generated by Django 5.1.1 on 2024-12-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_cart_total_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
